### ISSUE TITLE
Installing on Ubuntu 19.04, R 3.5.2

### ISSUE THREAD

**Issue by Gelsleichter** [philipp-baumann/simplerspec#4]
To easily install on ubuntu 19.04 with R 3.5.2, I run in linux terminal: 

$sudo add-apt-repository ppa:marutter/rrutter
$sudo apt-get update
$sudo apt-get install r-cran-rjags

the run in R 
devtools::install_github("philipp-baumann/simplerspec")

**Comment by philipp-baumann** [comment]
nice! using binary repositories speeds up :-)

**Comment by philipp-baumann** [comment]
see also Dirk's talk: https://www.youtube.com/watch?v=qIjWirNma-8

**Comment by philipp-baumann** [comment]
rjags seems to be needed from some downstream dependency, right? hasn't been the case before. I have ubuntu 18 and both `install.packages("rjags")` and apt-get install r-cran-rjags failed. apt-get install jags and then install.packages() did the job.

**Comment by Gelsleichter** [comment]
Hi, yes, there is something with dependencies. I said at begging, to "easily install", but actually, it was the only way that I could install.

**Comment by philipp-baumann** [comment]
Thanks for letting me know. I'll check out which of the packages in "Imports" imports rbugs. I'll add a note in the README, and eventually get rid of that dependency ;-)

**Comment by Gelsleichter** [comment]
Great! Thanks for the development :)
